

CREATE TABLE M_CAREER_PATHS (
  id bigint NOT NULL PRIMARY KEY,
  CD_JOB bigint NOT NULL,
  DT_START date NOT NULL,
  DT_END date NOT NULL,
  LB_COMMENT varchar(500)
);


CREATE TABLE R_SKILLS (
  id bigint NOT NULL PRIMARY KEY,
  LB_SKILL varchar(500) NOT NULL UNIQUE,
  CD_SKILL_TYPE bigint NOT NULL,
  CD_ACTIVITY bigint NOT NULL
);


CREATE TABLE R_QUALIFICATIONS (
  id bigint NOT NULL PRIMARY KEY,
  CD_QUALIFICATION varchar(500) NOT NULL UNIQUE,
  LB_QUALIFICATION varchar(500) NOT NULL,
  CD_QUALIF_TYPE bigint NOT NULL
);


CREATE TABLE R_ACTIVITIES (
  id bigint NOT NULL PRIMARY KEY,
  LB_ACTIVITY varchar(500) NOT NULL UNIQUE,
  CD_ACTIVITY_TYPE bigint NOT NULL
);


CREATE TABLE R_EMPLOYEES (
  id bigint NOT NULL PRIMARY KEY,
  CD_EMPLOYEE varchar(500) NOT NULL UNIQUE,
  LB_FIRSTNAME varchar(500) NOT NULL,
  LB_LASTNAME varchar(500) NOT NULL,
  LN_EMAIL varchar(500) NOT NULL UNIQUE,
  CD_GENDER bigint NOT NULL,
  CD_RANK bigint NOT NULL,
  CD_DOMAIN bigint NOT NULL,
  DT_JOIN date NOT NULL,
  DT_QUIT date NOT NULL,
  LB_ACTUAL_UNIT varchar(500) NOT NULL,
  DT_START date NOT NULL,
  DT_END date NOT NULL,
  LB_FUTURE_UNIT date,
  LB_COMMENT varchar(500)
);


CREATE TABLE R_MGS (
  id bigint NOT NULL PRIMARY KEY,
  CD_MGS varchar(500) NOT NULL UNIQUE
);


CREATE TABLE R_OU_ENVIRONMENTS (
  id bigint NOT NULL PRIMARY KEY,
  CD_OU_ENV varchar(500) NOT NULL,
  LB_OU_ENV varchar(500),
  LB_COLOR varchar(500) NOT NULL
);


CREATE TABLE R_ACTIVITY_TYPES (
  id bigint NOT NULL PRIMARY KEY,
  CD_ACTIVITY_TYPE varchar(500) NOT NULL UNIQUE,
  CD_ETR bigint NOT NULL
);


CREATE TABLE R_QUALIF_TYPES (
  id bigint NOT NULL PRIMARY KEY,
  CD_QUALIF_TYPE varchar(500) NOT NULL UNIQUE,
  LB_QUALIF_TYPE varchar(500)
);


CREATE TABLE R_REM (
  id bigint NOT NULL PRIMARY KEY,
  CD_ETR int NOT NULL UNIQUE,
  LB_ETR varchar(500) NOT NULL,
  CD_MGS varchar(500) NOT NULL
);


CREATE TABLE R_DOMAINS (
  id bigint NOT NULL PRIMARY KEY,
  CD_DOMAIN varchar(500) NOT NULL UNIQUE,
  LB_DOMAIN varchar(500) NOT NULL
);


CREATE TABLE R_ORGANISATIONAL_UNITS (
  id bigint NOT NULL PRIMARY KEY,
  CD_OU varchar(500) NOT NULL UNIQUE,
  LB_OU varchar(500),
  CD_NEXT_OU bigint,
  CD_OU_TYPE bigint NOT NULL
);


CREATE TABLE R_OU_TYPES (
  id bigint NOT NULL PRIMARY KEY,
  CD_OU_TYPE varchar(500) NOT NULL UNIQUE,
  LB_OU_TYPE varchar(500) NOT NULL UNIQUE
);


CREATE TABLE R_RANKS (
  id bigint NOT NULL PRIMARY KEY,
  CD_RANK varchar(500) NOT NULL UNIQUE,
  LB_RANK varchar(500),
  CD_RANK_CAT bigint NOT NULL
);


CREATE TABLE R_RANK_CAT (
  id bigint NOT NULL PRIMARY KEY,
  CD_RANK_CAT varchar(500) NOT NULL UNIQUE,
  LB_RANK_CAT varchar(500)
);


CREATE TABLE R_GENDERS (
  id bigint NOT NULL PRIMARY KEY,
  CD_GENDER varchar(500) NOT NULL UNIQUE,
  LB_GENDER varchar(500)
);


CREATE TABLE R_JOBS (
  id bigint NOT NULL PRIMARY KEY,
  CD_JOB varchar(500) NOT NULL UNIQUE,
  LB_ROLE varchar(500) NOT NULL,
  CD_DOMAIN bigint NOT NULL,
  CD_RANK bigint NOT NULL,
  CD_CAREER_PATH bigint NOT NULL,
  CD_ETR bigint NOT NULL,
  CD_OU bigint NOT NULL,
  DT_YEAR_NEED date NOT NULL,
  LB_COMMENT varchar(500)
);


CREATE TABLE M_STAGES (
  id bigint NOT NULL PRIMARY KEY,
  NB_INDEX int NOT NULL,
  LB_STAGE varchar(500) NOT NULL,
  CD_STAGE_TYPE bigint NOT NULL,
  CD_CAREER_PATH bigint NOT NULL,
  CD_OU bigint NOT NULL,
  NB_DURATION int NOT NULL
);


CREATE TABLE R_STAGE_TYPES (
  id bigint NOT NULL PRIMARY KEY,
  LB_STAGE_TYPE varchar(500) NOT NULL UNIQUE
);


CREATE TABLE M_AFFECTATIONS (
  id bigint NOT NULL PRIMARY KEY,
  CD_EMPLOYEE bigint NOT NULL PRIMARY KEY,
  CD_JOB bigint NOT NULL PRIMARY KEY
);


CREATE TABLE M_PROGRESS (
  id bigint NOT NULL PRIMARY KEY,
  CD_EMPLOYEE bigint NOT NULL PRIMARY KEY,
  CD_PROGRESS_STATUS bigint NOT NULL,
  CD_STAGE bigint NOT NULL PRIMARY KEY,
  DT_START date NOT NULL,
  DT_COMPLETION date,
  NB_COMPLETION_PERCENTAGE int NOT NULL
);


CREATE TABLE R_PROGRESS_STATUS (
  id bigint NOT NULL PRIMARY KEY,
  LB_PROGRESS_STATUS varchar(500) NOT NULL UNIQUE
);


CREATE TABLE M_JOB_QUALIFICATIONS (
  id bigint NOT NULL PRIMARY KEY,
  CD_JOB bigint NOT NULL PRIMARY KEY,
  CD_QUALIFICATION bigint NOT NULL PRIMARY KEY
);


CREATE TABLE R_SKILL_TYPES (
  id bigint NOT NULL PRIMARY KEY,
  LB_SKILL_TYPE varchar(500) NOT NULL
);


CREATE TABLE M_EMPLOYEE_QUALIFICATIONS (
  id bigint NOT NULL PRIMARY KEY,
  CD_EMPLOYEE bigint NOT NULL,
  CD_QUALIFICATION bigint NOT NULL,
  DT_OBTAINED date NOT NULL
);


CREATE TABLE M_EMPLOYEE_SKILLS (
  id bigint NOT NULL PRIMARY KEY,
  CD_EMPLOYEE bigint NOT NULL PRIMARY KEY,
  CD_SKILL bigint NOT NULL PRIMARY KEY,
  LB_COMMENT varchar(500)
);


ALTER TABLE R_ACTIVITIES ADD CONSTRAINT R_ACTIVITIES_CD_ACTIVITY_TYPE_fk FOREIGN KEY (CD_ACTIVITY_TYPE) REFERENCES R_ACTIVITY_TYPES (id);
ALTER TABLE R_ACTIVITY_TYPES ADD CONSTRAINT R_ACTIVITY_TYPES_CD_ETR_fk FOREIGN KEY (CD_ETR) REFERENCES R_REM (id);
ALTER TABLE R_DOMAINS ADD CONSTRAINT R_DOMAINS_id_fk FOREIGN KEY (id) REFERENCES R_EMPLOYEES (CD_DOMAIN);
ALTER TABLE R_DOMAINS ADD CONSTRAINT R_DOMAINS_id_fk FOREIGN KEY (id) REFERENCES R_JOBS (CD_DOMAIN);
ALTER TABLE R_REM ADD CONSTRAINT R_ETR_id_fk FOREIGN KEY (id) REFERENCES R_JOBS (CD_ETR);
ALTER TABLE R_GENDERS ADD CONSTRAINT R_GENDERS_id_fk FOREIGN KEY (id) REFERENCES R_EMPLOYEES (CD_GENDER);
ALTER TABLE R_MGS ADD CONSTRAINT R_MGS_CD_MGS_fk FOREIGN KEY (CD_MGS) REFERENCES R_REM (CD_MGS);
ALTER TABLE R_ORGANISATIONAL_UNITS ADD CONSTRAINT R_ORGANISATIONAL_UNITS_CD_NEXT_OU_fk FOREIGN KEY (CD_NEXT_OU) REFERENCES R_ORGANISATIONAL_UNITS (id);
ALTER TABLE R_ORGANISATIONAL_UNITS ADD CONSTRAINT R_ORGANISATIONAL_UNITS_CD_OU_TYPE_fk FOREIGN KEY (CD_OU_TYPE) REFERENCES R_OU_TYPES (id);
ALTER TABLE R_ORGANISATIONAL_UNITS ADD CONSTRAINT R_ORGANISATIONAL_UNITS_id_fk FOREIGN KEY (id) REFERENCES R_JOBS (CD_OU);
ALTER TABLE R_OU_ENVIRONMENTS ADD CONSTRAINT R_OU_TYPES_id_fk FOREIGN KEY (id) REFERENCES R_ORGANISATIONAL_UNITS (CD_OU_TYPE);
ALTER TABLE R_QUALIFICATIONS ADD CONSTRAINT R_QUALIFICATIONS_CD_QUALIF_TYPE_fk FOREIGN KEY (CD_QUALIF_TYPE) REFERENCES R_QUALIF_TYPES (id);
ALTER TABLE R_RANKS ADD CONSTRAINT R_RANKS_CD_RANK_CAT_fk FOREIGN KEY (CD_RANK_CAT) REFERENCES R_RANK_CAT (id);
ALTER TABLE R_RANKS ADD CONSTRAINT R_RANKS_id_fk FOREIGN KEY (id) REFERENCES R_JOBS (CD_RANK);
ALTER TABLE R_RANKS ADD CONSTRAINT R_RANKS_id_fk FOREIGN KEY (id) REFERENCES R_EMPLOYEES (CD_RANK);
ALTER TABLE R_SKILLS ADD CONSTRAINT R_SOFTSKILLS_CD_ACTIVITY_fk FOREIGN KEY (CD_ACTIVITY) REFERENCES R_ACTIVITIES (id);
ALTER TABLE M_STAGES ADD CONSTRAINT M_STAGES_CD_STAGE_TYPE_fk FOREIGN KEY (CD_STAGE_TYPE) REFERENCES R_STAGE_TYPES (id);
ALTER TABLE R_JOBS ADD CONSTRAINT R_JOBS_CD_CAREER_PATH_fk FOREIGN KEY (CD_CAREER_PATH) REFERENCES M_CAREER_PATHS (id);
ALTER TABLE M_STAGES ADD CONSTRAINT M_STAGES_CD_CAREER_PATH_fk FOREIGN KEY (CD_CAREER_PATH) REFERENCES M_CAREER_PATHS (id);
ALTER TABLE M_PROGRESS ADD CONSTRAINT M_PROGRESS_CD_EMPLOYEE_fk FOREIGN KEY (CD_EMPLOYEE) REFERENCES R_EMPLOYEES (id);
ALTER TABLE M_PROGRESS ADD CONSTRAINT M_PROGRESS_CD_STAGE_fk FOREIGN KEY (CD_STAGE) REFERENCES M_STAGES (id);
ALTER TABLE M_PROGRESS ADD CONSTRAINT M_PROGRESS_CD_PROGRESS_STATUS_fk FOREIGN KEY (CD_PROGRESS_STATUS) REFERENCES R_PROGRESS_STATUS (id);
ALTER TABLE M_JOB_QUALIFICATIONS ADD CONSTRAINT M_JOB_QUALIFICATIONS_CD_JOB_fk FOREIGN KEY (CD_JOB) REFERENCES R_JOBS (id);
ALTER TABLE M_JOB_QUALIFICATIONS ADD CONSTRAINT M_JOB_QUALIFICATIONS_CD_QUALIFICATION_fk FOREIGN KEY (CD_QUALIFICATION) REFERENCES R_QUALIFICATIONS (id);
ALTER TABLE M_STAGES ADD CONSTRAINT M_STAGES_CD_OU_fk FOREIGN KEY (CD_OU) REFERENCES R_ORGANISATIONAL_UNITS (id);
ALTER TABLE M_EMPLOYEE_QUALIFICATIONS ADD CONSTRAINT M_EMPLOYEE_QUALIFICATIONS_CD_QUALIFICATION_fk FOREIGN KEY (CD_QUALIFICATION) REFERENCES R_QUALIFICATIONS (id);
ALTER TABLE M_EMPLOYEE_QUALIFICATIONS ADD CONSTRAINT M_EMPLOYEE_QUALIFICATIONS_CD_EMPLOYEE_fk FOREIGN KEY (CD_EMPLOYEE) REFERENCES R_EMPLOYEES (id);
ALTER TABLE M_AFFECTATIONS ADD CONSTRAINT M_AFFECTATIONS_CD_EMPLOYEE_fk FOREIGN KEY (CD_EMPLOYEE) REFERENCES R_EMPLOYEES (id);
ALTER TABLE M_AFFECTATIONS ADD CONSTRAINT M_AFFECTATIONS_CD_JOB_fk FOREIGN KEY (CD_JOB) REFERENCES R_JOBS (id);
ALTER TABLE M_EMPLOYEE_SKILLS ADD CONSTRAINT M_EMPLOYEE_SKILLS_CD_EMPLOYEE_fk FOREIGN KEY (CD_EMPLOYEE) REFERENCES R_EMPLOYEES (id);
ALTER TABLE M_EMPLOYEE_SKILLS ADD CONSTRAINT M_EMPLOYEE_SKILLS_CD_SKILL_fk FOREIGN KEY (CD_SKILL) REFERENCES R_SKILLS (id);
ALTER TABLE R_SKILLS ADD CONSTRAINT R_SKILLS_CD_SKILL_TYPE_fk FOREIGN KEY (CD_SKILL_TYPE) REFERENCES R_SKILL_TYPES (id);
